### ISSUE TITLE
preLoader property no longer exists

### ISSUE THREAD

**Issue by JamesDaniel** [joeeames/WebpackFundamentalsCourse#12]
The property preLoader no longer exists for the webpack configuration file. I was getting this error:
```
configuration.module has an unknown property 'preLoaders'.
```
I found a solution to this problem here:
http://stackoverflow.com/questions/39668579/webpack-2-1-0-beta-25-error-unknown-property-postloaders

So the code:
```javascript
module.exports = {
    entry: ["./utils", "./app.js"],
    output: {
        filename: "bundle.js"
    },
    watch: true,

    module: {
        preLoaders: [
            {
                test: /\.js$/, // include .js files
                exclude: /node_modules/, // exclude any and all files in the node_modules folder
                loader: "jshint-loader"
            }
        ],
        loaders: [
            {
                test: /\.es6$/,
                exclude: /node_modules/,
                loader: "babel-loader"
            }
        ]
    },
    resolve: {
        extensions: ['.js','.es6']
    }
}
```
Should now look like this:
```javascript
module.exports = {
    entry: ["./utils", "./app.js"],
    output: {
        filename: "bundle.js"
    },
    watch: true,

    module: {
        loaders: [
            {
                test: /\.es6$/,
                exclude: /node_modules/,
                loader: "babel-loader"
            },
            {
                test: /\.js$/,
                exclude: /node_modules/,
                loader: "jshint-loader",
                enforce: 'pre'
            }
        ]
    },
    resolve: {
        extensions: ['.js','.es6']
    }
}
```
This is from the pluralsight tutorials:
https://app.pluralsight.com/player?course=webpack-fundamentals&author=joe-eames&name=webpack-fundamentals-m2&clip=6&mode=live
### Using Preloaders

Because of this the tutorials are no longer up to date with the latest version of webpack.

**Comment by joeeames** [comment]
ok, I'll update the readme to include this note.

**Comment by joeeames** [comment]
I've incorporated this into the course readme and marked the course as out of date. I'm going to close this issue.

**Comment by hanguyenk** [comment]
The `module.loaders` is now `module.rules`. Although the old naming convention is still valid, I think we should have some notes about that.
FYI: https://webpack.js.org/guides/migrating/#module-loaders-is-now-module-rules
