### ISSUE TITLE
This course is NOT out of date. as of 12/21/2016

### ISSUE THREAD

**Issue by Luis-Palacios** [joeeames/WebpackFundamentalsCourse#8]
What you are mentioning in the readme file about the course being out of date, is no longer true, I just saw the clip about Using loaders and is using babel 6, with configuration file and necessary plugins.

**Comment by joeeames** [comment]
are you saying that the latest version of everything works fine with the code as presented in the course?

**Comment by Luis-Palacios** [comment]
I've just finished and did not have any problems, using the latest node js LTS version and doing simple npm install without specifying the version.

Great course btw thanks!
